apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
      tier: backend
  template:
    metadata:
      labels:
        app: patient-service
        tier: backend
    spec:
      containers:
        - name: patient-service
          image: bstar999/patient-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: BILLING_SERVICE_ADDRESS
              value: billing-service
            - name: BILLING_SERVICE_GRPC_PORT
              value: "9001"
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://pgsql-cluster-rw.postgresql.svc.cluster.local:5432/myapp
            - name: SPRING_DATASOURCE_USERNAME
              value: myuser
            - name: SPRING_DATASOURCE_PASSWORD
              value: s3cr3t
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: SPRING_SQL_INIT_MODE
              value: always
            - name: SPRING_PROFILES_ACTIVE
              value: docker