apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: utils-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/mohamedbstar413/homelab.git
        revision: HEAD
        directories:
          - path: utils        # Match all direct subdirs of utils
  template:
    metadata:
      name: '{{path.basename}}'      # e.g., frontend
    spec:
      project: default
      source:
        repoURL: https://github.com/mohamedbstar413/homelab.git
        targetRevision: HEAD
        path: '{{path}}'        # {{path}} = microservices/auth-service
      destination:
        server: https://kubernetes.default.svc
        namespace: 'argocd'              # All apps will be deployed to the 'argocd' namespace
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true