apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/mohamedbstar413/homelab.git
    targetRevision: main
    path: utils/longhorn

  destination:
    server: https://kubernetes.default.svc
    namespace: 'longhorn-system'

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true