apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: pgsql-cluster
spec:
  instances: 1

  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"

  bootstrap:
    initdb:
      database: myapp
      owner: myuser
      secret:
        name: myuser-secret     # k8s secret with credentials

  storage:
    size: 1Gi
    storageClass: lh-wfc-ret-sc

  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1"