apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: admin-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: "*"
          patternType: literal
        operations: [Read, Write, Create, Describe, Delete]
      - resource:
          type: group
          name: "*"
          patternType: literal
        operations: [Read, Describe]