apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lh-wfc-ret-sc

provisioner: driver.longhorn.io

allowVolumeExpansion: true
reclaimPolicy: Retain

parameters:
  numberOfReplicas: "1"

volumeBindingMode: WaitForFirstConsumer