apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
      app: analytics-service
  template:
    metadata:
      labels:
        tier: backend
        app: analytics-service
    spec:
      containers:
        - name: analytics-service
          image: bstar999/analytics-service:latest
          ports:
            - containerPort: 4002